version: "3.7"

services:
  app:
    build:
      context: .
    command: php -S 0.0.0.0:8080 ./public/index.php
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
    depends_on:
      - mysql

  mysql:
    image: 'mysql:5.7'
    restart: 'always'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
